default: &default
  adapter:  postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool:     <%= ENV.fetch("POSTGRES_POOL",     "15") %>
  host:     <%= ENV.fetch("POSTGRES_HOST",     "localhost") %>
  port:     <%= ENV.fetch("POSTGRES_PORT",     "5432") %>
  username: <%= ENV.fetch("POSTGRES_USER",     "uppertown") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "testpass") %>

test:
  <<: *default
  database: webapp_test
  migrations_paths: db/migrate

development:
  primary:
    <<: *default
    database: webapp_development
    schema_dump: schema.rb
    migrations_paths: db/migrate
  queue:
    <<: *default
    database: webapp_development_queue
    schema_dump: queue_schema.rb
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: webapp_development_cache
    schema_dump: cache_schema.rb
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: webapp_development_cable
    schema_dump: cable_schema.rb
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: webapp_production
    schema_dump: schema.rb
    migrations_paths: db/migrate
  queue:
    <<: *default
    database: webapp_production_queue
    schema_dump: queue_schema.rb
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: webapp_production_cache
    schema_dump: cache_schema.rb
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: webapp_production_cable
    schema_dump: cable_schema.rb
    migrations_paths: db/cable_migrate
